FROM openwhisk/python3action

RUN pip install objcrypt
RUN pip install Crypto
RUN pip install pycrypto

# ceph + redis packages
RUN pip install boto
RUN pip install redis
RUN pip install redis-py-cluster
